# 站点模式
# -------------------------------------------
mode: auto  # 根据系统自动切换暗黑或亮色模式

# 头像设置
# -------------------------------------------
avatar:
  url: /images/avatar.jpg
  status:
    enable: false  # 禁用状态显示

# 首页 Banner 配置
# -------------------------------------------
banner:
  enable: true  # 启用 Banner
  title:        # 首页 Banner 显示的标题
    - 塑
    - 方
  border: false  # 关闭 Banner 边框
  cloud:
    enable: true   # 启用云动画效果
    color: white   # 云的颜色
  go_down:
    enable: true   # 启用向下滚动的箭头
    icon: icon-arrow-down-s-line  # 箭头的图标

bg_image:
  enable: false

# 评论系统配置
# -------------------------------------------
comment:
  candidates:  # 评论系统候选
    - waline   # 使用 Waline 评论系统
    # - giscus  # (注释) 另一个候选评论系统
  tips:  # 自定义评论系统提示
    - 如果您有任何关于博客内容的相关讨论，欢迎前往 <a href="https://github.com/YunYouJun/yunyoujun.github.io/discussions" target="_blank">GitHub Discussions</a> 与我交流。

waline:
  enable: true  # 启用 Waline 评论系统
  serverURL: https://waline.yunyoujun.cn  # Waline 服务器地址
  visitor: true  # 显示访客信息
  comment: true  # 启用评论功能
  emoji:  # 自定义 Emoji 表情
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/bilibili/
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/weibo/
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/qq/
  locale:
    placeholder: 填写邮箱，可以收到回复通知哦～  # 评论框的占位提示
  requiredMeta: [nick]  # 必填的用户信息字段，昵称为必填

# 页脚配置
# -------------------------------------------
footer:
  since: 2024  # 博客开始年份
  icon:
    animated: false
    color: '#0078E7'
  powered:
    enable: false


albums:
  enable: true  # 启用相册功能

pages:


# 菜单配置
# -------------------------------------------
menu:
  custom:
    title: 留言板
    path: /about/#comment
    icon: ri:clipboard-line

# 鼠标动画效果
# -------------------------------------------
cursor:
  enable: true  # 启用鼠标动画效果

reward:
  enable: false  # 关闭打赏功能

  # 标签与分类颜色配置
# -------------------------------------------
tags:
  动画: crimson
  漫画: orange
  Parcel: '#21374b'
  学习: saddlebrown
  MAD: crimson
  教程: royalblue
  笔记: dimgray
  分享: '#0078e7'
  随笔: mediumpurple
  Blender: '#d04d2d'
  Linux: '#2577b1'
  中传: '#ccb44b'
  部落: '#DD306A'
  科幻: midnightblue
  蚂蚁森林: '#54a892'


# Google Tag Manager 配置
# -------------------------------------------
google_tagmanager:
  enable: true  # 启用 Google Tag Manager
  id: GTM-M9KWR9L  # GTM ID

status:
  enable: false  # 禁用状态图标显示


# 文章字数统计
# -------------------------------------------
wordcount:
  enable: true  # 启用文章字数统计

# 自定义说说 API
# -------------------------------------------
say:
  api: https://el-bot-api.vercel.app/api/words/young  # API 地址
  hitokoto:
    enable: false  # 启用一言

# 社交媒体链接
# -------------------------------------------
social:
  - name: E-Mail
    link: mailto:fengshancui@outlook.com # 邮件链接
    icon: ri:mail-line
    color: '#8E71C1'
  - name: 微博
    link: https://weibo.com/u/6417242173 # 微博链接
    icon: ri:weibo-line
    color: '#E6162D'
  - name: 网易云音乐
    link: https://music.163.com/#/user/home?id=1289342800  # 网易云音乐链接
    icon: ri:netease-cloud-music-line
    color: '#C20C0C'
 
